services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: iis
    environment:
      - POSTGRES_USER=husic
      - POSTGRES_PASSWORD=husic
      - POSTGRES_DB=iis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:80"
    depends_on:
      - app

volumes:
  postgres_data:
