version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: iis
    environment:
      - POSTGRES_USER=husic
      - POSTGRES_PASSWORD=husic
      - POSTGRES_DB=iis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: