"""Cascades

Revision ID: 1848c8901c46
Revises: 218668feed3f
Create Date: 2024-10-20 14:19:55.187894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1848c8901c46'
down_revision = '218668feed3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint('requests_veterinarian_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('requests_animal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animals', ['animal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['veterinarian_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint('reservations_animal_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reservations_volunteer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['volunteer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'animals', ['animal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservations_volunteer_id_fkey', 'users', ['volunteer_id'], ['id'])
        batch_op.create_foreign_key('reservations_animal_id_fkey', 'animals', ['animal_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('requests_animal_id_fkey', 'animals', ['animal_id'], ['id'])
        batch_op.create_foreign_key('requests_veterinarian_id_fkey', 'users', ['veterinarian_id'], ['id'])

    # ### end Alembic commands ###
