"""Add reservated to wwalk schedule

Revision ID: 1f3e3a74a564
Revises: 34132cd536f8
Create Date: 2024-11-24 16:55:18.573894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3e3a74a564'
down_revision = '34132cd536f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservated', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walking_schedules', schema=None) as batch_op:
        batch_op.drop_column('reservated')

    # ### end Alembic commands ###
