"""cascade

Revision ID: 218668feed3f
Revises: b985df6c2d86
Create Date: 2024-10-20 14:17:01.343557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218668feed3f'
down_revision = 'b985df6c2d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint('medical_records_veterinarian_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('medical_records_animal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animals', ['animal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['veterinarian_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('medical_records_animal_id_fkey', 'animals', ['animal_id'], ['id'])
        batch_op.create_foreign_key('medical_records_veterinarian_id_fkey', 'users', ['veterinarian_id'], ['id'])

    # ### end Alembic commands ###
