"""nullable vet in medrecord

Revision ID: 34132cd536f8
Revises: 1848c8901c46
Create Date: 2024-10-20 15:22:57.114943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34132cd536f8'
down_revision = '1848c8901c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('veterinarian_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('medical_records_veterinarian_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['veterinarian_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('medical_records_veterinarian_id_fkey', 'users', ['veterinarian_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('veterinarian_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
